<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.10.0" />
    <PackageReference Include="Gridify" Version="2.14.2" />
    <PackageReference Include="Gridify.EntityFramework" Version="2.14.2" />
    <PackageReference Include="MediatR" Version="11.1.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Handlers\Consultas\Commands\Delete\" />
	  <Folder Include="Handlers\Consultas\Commands\Update\" />
	  <Folder Include="Handlers\Consultas\Queries\GetConsultaById\" />
	  <Folder Include="Handlers\Equipes\Commands\Delete\" />
	  <Folder Include="Handlers\Equipes\Commands\Update\" />
	  <Folder Include="Handlers\Equipes\Queries\GetEquipeById\" />
	  <Folder Include="Handlers\Relatorio\Commands\" />
	  <Folder Include="Handlers\Salas\Commands\Delete\" />
	  <Folder Include="Handlers\Salas\Queries\GetSalaById\" />
	</ItemGroup>

</Project>
